### ISSUE TITLE
Persisting last token time and value

### ISSUE THREAD

**Issue by alekop** [alexalok/dotAPNS#21]
I'm recreating the ApnsClient class when needed and then disposing of it, so there is no permanent instance to keep track of the last token and generation time. It seems to be working so far - I am able to send multiple messages in a short period without errors - but I'm not sure if this is something I should be concerned about.

**Comment by alexalok** [comment]
While it works since each ApnsClient instance generates its own JWT, I suggest you to keep an eye on possible failures as  [APNs docs](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/establishing_a_token-based_connection_to_apns) states that
> APNs reports an error if you recreate your tokens more than once every 20 minutes.

If the failures happen indeed, please report here and I will work on a solution to persist a JWT for your use-case.

**Comment by alexalok** [comment]
Closing the issue since no feedback has been provided. If there's something to update me on, please feel free to reopen it.
