### ISSUE TITLE
How to sent image in push notification using this library

### ISSUE THREAD

**Issue by Trushal0066** [alexalok/dotAPNS#35]
I want to send image in APNS payload using this library

**Comment by alexalok** [comment]
Hi,

there is no built-in way to do so. The reason is that APNs itself does not has any features to support your case directly. You may use the following solutions:

1. Host an image somewhere and send a URL in a payload. Upon receiving, your app can download the image by reading the URL provided.
2. Base64-encode the image and send it in a payload. Upon receiving, your app can base64-decode it and store either in RAM or write on disk.
3. Store the images you might need in the application resources beforehand with the specific names and send one of those names in the payload so that your app knows which image to show/load.

You can add custom attributes to the payload using the `ApplePush.AddCustomProperty` method, refer to [this comment](https://github.com/alexalok/dotAPNS/issues/32#issuecomment-690982060) for examples.
