### ISSUE TITLE
Refresh Your Token Regularly

### ISSUE THREAD

**Issue by penguinawesome** [alexalok/dotAPNS#38]
Hi,

It is stated in the APNS documentation that when using Token based, it should be refresh at least once per 60 mins: https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/establishing_a_token-based_connection_to_apns

Can i instantiate then reuse the APNS client up to more or less 50 mins? Then create a new one again after 50 mins and so forth? Is it thread safe? Like we plan to use the same APNS client from a multi thread?

**Comment by alexalok** [comment]
Hi,

thank you for your questions. I'll address them separately.

> Can i instantiate then reuse the APNS client up to more or less 50 mins?

Yes, ApnsClient automatically refreshes JWT token every 20 minutes ([source](https://github.com/alexalok/dotAPNS/blob/047a869e662158efa64f33da040eeef0f9bae379/dotAPNS/ApnsClient.cs#L268)).

>  Then create a new one again after 50 mins and so forth?

Since you can reuse the single ApnsClient instance there's really no need to reinstantiate it. But you may do so if you want.

> Is it thread safe?

Well, not really. The `Send()` method calls `GetOrGenerateJwt()` ([source](https://github.com/alexalok/dotAPNS/blob/047a869e662158efa64f33da040eeef0f9bae379/dotAPNS/ApnsClient.cs#L120)) which is in turn not thread-safe. As a result multiple JWT tokens may be created at the very beginning of push sending and/or when JWT token is recreated due to its expiration. Depending on how many parallel sends there are you may hit JWT recreation limit and APNs will temporary block you from sending pushes altogether. 

If you would like `Send()` method to be 100% thread-safe please don't hesitate to ask me.

**Comment by penguinawesome** [comment]
Alright i see that i can reuse the APNSClient for my entire application lifetime, however i need to re-instantiate this every 5 minutes perhaps since i need to pass a new httpClient for every 5 mins (Due to DNS issue and etc. i am using httpclientFactory for generating httpClient which happens to generate once every 5mins). 

Since APNSClient  is reusable for the entire application lifetime, i hope there is a method or way to inject the new httpClient to be use, since the httpClient needs to be refresh and re-instantiate every 5 minutes or X mins (This is based on the known issue of httpclient DNS issue etc.).

And yes we are using the APNSClient.Send() method from different multiple threads since we are pushing a lot of notifications, then we need to set it up a multi thread. Multi thread with same APNSClient reference only. I hope this can be ThreadSafe and reusable from multiple threads for higher concurrency and speed :) Thank you so much for creating this library. This really help us migrating from PushSharp (old APNS API -- will be deprecated after nov 2020)

**Comment by alexalok** [comment]
> i am using httpclientFactory for generating httpClient which happens to generate once every 5mins

Just a nitpick, but technically `HttpClientFactory` generates a new `HttpClient` instance every time it is requested ([source](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1#httpclient-and-lifetime-management)). `HttpMessageHandler` is what really gets reused here. With default settings, factory creates a new `HttpClient` with one of the `HttpMessageHandler`s from the pool. When `HttpClient` gets recycled its `HttpMessageHandler` is released back to the pool. If `HttpMessageHandler` is expired (2 minutes by default, [source](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1#httpclient-and-lifetime-management)) then it is removed from the pool altogether and a new handler is created.

> i hope there is a method or way to inject the new httpClient to be use

Unfortunately, there isn't currently, so you might want to reinstantiate `ApnsClient` every now and then. Even so, I doubt APNs DNS changes so frequently that it poses a problem. Feel free to prove me otherwise though. For now, I'm not prioritizing this due to the reason stated. If you feel adventurous, a PR can be done that I'd gladly accept.

> I hope this can be ThreadSafe and reusable from multiple threads for higher concurrency and speed :)

I'll try to work on that but no definite ETA can be given.

> Thank you so much for creating this library. 

Thanks and thank you for using it as well 👍

**Comment by penguinawesome** [comment]
I agree, i also doubt that APNS DNS changes so frequently, but just for assurance since you'll never know if you hit their maintenance or auto failover :) 

Maybe making the Send() method thread safe would be the ideal solution for here :). Thanks! Looking forward for the new updates.

**Comment by alexalok** [comment]
I've extracted the results of our discussion here to the separate issues so closing this one.
