### ISSUE TITLE
There is no information about 3.x.x versions.

### ISSUE THREAD

**Issue by i5kender** [alexalok/dotAPNS#50]
Hello,
I am using 2.6.1 version but you have published 3.x.x versions. 
I can not find any information about what happens in 3.x.x versions.

* What should I pay attention to when using 3.x versions?
* What are the new features?

Best Regards.

**Comment by alexalok** [comment]
Hello,

3.0 introduced a breaking change by renaming `Send` method to `SendAsync` so that it is more obvious to the consumers that the method is indeed asynchronous (https://github.com/alexalok/dotAPNS/commit/17857447ae8125516a5ec4180032811498a86180).
There was also a possible deadlock fixed (https://github.com/alexalok/dotAPNS/commit/f7e17d178cbb632dbc7f4d90ba16fb110263a3bb).

**Comment by i5kender** [comment]
Thank you @alexalok for replying. 
If you add firebase support, we will get rid of the pushsharp library completely.

Do you have such an opinion? (Firebase)

Best regards.

**Comment by alexalok** [comment]
Unfortunately not, dotAPNS only targets APNs and APNs only. Supporting other push providers is currently not planned. 

As for Firebase, there's an official library available: https://github.com/firebase/firebase-admin-dotnet, so I don't see the point in re-implementing what's already available.

**Comment by alexalok** [comment]
Is there anything else you would like to know? Feel free to do so, otherwise please close the issue. Thanks!
