### ISSUE TITLE
Support multiple apps from single server

### ISSUE THREAD

**Issue by mubaraknet** [alexalok/dotAPNS#56]
I'm having a Push Notification server in .Net Framework and I want to use the same server for multiple apps under my Apple developer account. Since I cannot use the .p12 certificate, is there a way to achieve this using the token based mechanism?

Why I'm asking is, I saw the JWT token requires the bundle ID, and if so I may need to make different builds for each of my applications. 

As of now, I'm using PushSharp (which doesn't support HTTP/2 based APNS) and .p12 certificate. So I can use one build and differentiate each client by giving in their respective APNS certificate. 

Is there any solution other making different builds with each Bundle ID?

Thanks

**Comment by alexalok** [comment]
> Is there any solution other making different builds with each Bundle ID?

Sure thing! Just create multiple `ApnsClient` instances, passing a different `ApnsJwtOptions` options to each. For example:

```c#
var jwt1 = new ApnsJwtOptions() { BundleId = "bundle1", CertContent = "certContent1", KeyId = "key1", TeamId = "team1" };
var jwt2 = new ApnsJwtOptions() { BundleId = "bundle2", CertContent = "certContent2", KeyId = "key2", TeamId = "team2" };

var apnsClient1 = ApnsClient.CreateUsingJwt(new HttpClient(), jwt1);
var apnsClient2 = ApnsClient.CreateUsingJwt(new HttpClient(), jwt2);

await apnsClient1.SendAsync(new ApplePush(ApplePushType.Alert).AddAlert("Push for app #1"));
await apnsClient2.SendAsync(new ApplePush(ApplePushType.Alert).AddAlert("Push for app #2"));
```

**Comment by BillInOKC** [comment]
I hope you will allow me to respond to this, because this is precisely what I have been doing. I have three enterprise iOS apps, each of which needs to respond to two Push Notifications sources, one each for a TCP server and an ASP.NET web page --  totaling six sources. (I will be adding two more in the near future.)

What I have done is create a single application containing Alex's dotAPNS library that runs on a server that will process Push Notifications from all of the sources. This allows me to have one location for the certificate, the key id, and the team id (since they never change), and then each sending application sends the bundle ID along with the rest of the message information (i.e., message title, subtitle, body, device code, etc.). In my case, the sending applications place all the message information into an .xml file and send it to the APNS application, which runs it through an .xml reader. It works beautifully.

And I'd like to take this opportunity to say how much I appreciate Alex's work on this library. It's awesome, and that is a word I do not use often.

If you have further questions, I'll be glad to help.

**Comment by mubaraknet** [comment]
Thank you @alexalok for the quick response and example. And @BillInOKC , I appreciate the time you took to explain in detail how you implemented it, and thank you very much. 

❤
