### ISSUE TITLE
JWT Expiration

### ISSUE THREAD

**Issue by JasonCavendish** [alexalok/dotAPNS#64]
How does the dotAPNS package handle JWT expiration?

**Comment by alexalok** [comment]
ApnsClient refreshes the JWT automatically within the correct time range. For more details, refer to the [source code](https://github.com/alexalok/dotAPNS/blob/67df97d0e9025acd2f4b94cb70dab05116ed4552/dotAPNS/ApnsClient.cs#L296).

Using multiple ApnsClient instances with the single APNs certificate is not supported because it would lead to multiple JWTs being generated and refreshed simultaneously. This may or may not hit the rate-limit set by APNs. Sharing a single JWT between multiple ApnsClient instances and/or processes is currently not supported.

**Comment by JasonCavendish** [comment]
Can the JWTs be expired immediately after the request?
Wouldn't that support multiple instance use?

**Comment by alexalok** [comment]
As per [APNs documentation](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/establishing_a_token-based_connection_to_apns) (_Refresh Your Token Regularly_ section):

> ... APNs reports an error if you recreate your tokens more than once every 20 minutes.
