### ISSUE TITLE
APNS Header Information

### ISSUE THREAD

**Issue by Bluesky13503** [alexalok/dotAPNS#67]
Hi, 
can someone help me with the Header properties which apple offer?

Iam looking for the Following:

apns-topic
apns-collapse-id
apns-priority
apns-expiration
apns-id
apns-push-type

https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns/

I found ApplePushType, Priority which I guess are apns-push-type and apns-priority, but what about the others?
Do I have to add them though AddCustomProperty??

**Comment by alexalok** [comment]
Hi!

`apns-topic` is set automatically by the library ([source](https://github.com/alexalok/dotAPNS/blob/67df97d0e9025acd2f4b94cb70dab05116ed4552/dotAPNS/ApnsClient.cs#L280)).

For `apns-collapse-id` use `push.AddCollapseId("test_collapse_id");` ([source](https://github.com/alexalok/dotAPNS/blob/0742dc04257584640cd419a58d3a5244559c3409/dotAPNS.Tests/ApnsClient_Tests.cs#L189)).

`apns-priority` is set automatically but you can overwrite it by calling `push.SetPriority(10);` ([source](https://github.com/alexalok/dotAPNS/blob/67df97d0e9025acd2f4b94cb70dab05116ed4552/dotAPNS.Tests/ApplePush_Tests.cs#L122)).

`apns-expiration` is set by default to "immediately expire", which means that if APNs cannot deliver push immediately it is discarded. You can set a custom expiration time by calling `push.AddExpiration(DateTimeOffset.UtcNow.AddHours(1));` ([source](https://github.com/alexalok/dotAPNS/blob/67df97d0e9025acd2f4b94cb70dab05116ed4552/dotAPNS.Tests/ApplePush_Tests.cs#L145)).

`apns-id` is not supported.

`apns-push-type` is set from the value you provide when constructing a push instance ([source](https://github.com/alexalok/dotAPNS/blob/67df97d0e9025acd2f4b94cb70dab05116ed4552/dotAPNS.Tests/ApplePush_Tests.cs#L34)).

You currently cannot add `apns-id` because it must be set in headers. You can however set any arbitrary fields inside a push's body by calling `.AddCustomProperty("customPropertyKey", "customPropertyValue");` ([source](https://github.com/alexalok/dotAPNS/blob/67df97d0e9025acd2f4b94cb70dab05116ed4552/dotAPNS.Tests/ApplePush_Tests.cs#L94)).

**Comment by AndyBond2007** [comment]
Is there any plan to add apns-id support?

Use Case: 

Sending a notification which you later wish to "remove" as the status of something has updated (maybe a notification  has been acknowledged from another device)

set the apns-id (or retrieve from response), and send a standard message.

if then need to cancel the message you can send with the same apps-id, but with content-available, this will effectively remove the notification from the device.
