### ISSUE TITLE
var response = await apns.Send(push); 

### ISSUE THREAD

**Issue by michaweiss10** [alexalok/dotAPNS#74]
I get the message:
the await operator can only be used within an async method

**Comment by michaweiss10** [comment]
using System; 
using System.Net.Http;
using System.Threading.Tasks;
using Newtonsoft;
using dotAPNS;


 


public static class Snippet
{
	public static void SendToiOS()
	{
		
		var options = new ApnsJwtOptions() 
		{
	    BundleId = "BBB", 
    	CertContent = "-----BEGIN PRIVATE KEY-----GGGG-----END PRIVATE KEY-----", 
    	//CertFilePath = "", // use either CertContent or CertFilePath, not both
    	KeyId = "KKK", 
    	TeamId = "TTT"
		};	
		
		var apns = ApnsClient.CreateUsingJwt(new HttpClient(new WinHttpHandler()), options); 
		var push = new ApplePush(ApplePushType.Alert)
    		.AddAlert("HUJIapp", "YYYYYbody")
    		.AddToken("FFF767aeb1d83d35a12c4308ee3b1483c5e2ffbe41d77e1186fae5023b72e6b");

		try
		{
			
		var response = await apns.Send(push);
		
			
			
			
		if (response.IsSuccessful)
			
		{
			Console.WriteLine("An alert push has been successfully sent!");
		}
		else
		{
			switch (response.Reason)
			{
				case ApnsResponseReason.BadCertificateEnvironment:
					// The client certificate is for the wrong environment.
					// TODO: retry on another environment
					break;
					// TODO: process other reasons we might be interested in
				default:
					throw new ArgumentOutOfRangeException(nameof(response.Reason), response.Reason, null);
					
			}
			Console.WriteLine("Failed to send a push, APNs reported an error: " + response.ReasonString);
		
		}
	}
	catch (TaskCanceledException)
	{
		Console.WriteLine("Failed to send a push: HTTP request timed out.");
	}
	catch (HttpRequestException ex)
	{
		Console.WriteLine("Failed to send a push. HTTP request failed: " + ex);
	}		
	
	}

}

**Comment by michaweiss10** [comment]
What is wrong with the code?

**Comment by burhan1875** [comment]
You have top declare your method as async:

"public static async void SendToiOS()"

**Comment by alexalok** [comment]
As @burhan1875 correctly stated, you need to declare your containing method as `async`. 
I highly recommend getting familiar with TAP (task asynchronous programming model) first. [Click here](https://www.c-sharpcorner.com/article/async-and-await-in-c-sharp/) to learn more.

**Comment by BillInOKC** [comment]
I would like to share a discovery I made that is an alternative to enclosing the method in an ASYNC wrapper. To clarify, I am doing this in VB.net, so I am not sure if it is suitable for C. 

I found that enclosing the entire block in an async function made it difficult to get returns from the push process, which I needed in order to determine the success or failure of the push notifications. An async `Function`  must return a `Task` or `Task(of TResult)` variable. I was never able to get the the kind of information I needed from a `Task` or `Task(of TResult)`.  (I'm just not that smart.)

Instead, I have been using the `SendAsync` method, which requires only one line in the sending block, thus:

     Dim apns as ApnsClient=ApnsClient.CreateUsingJWT(httpclient, APNSoptions)
     Dim push As New ApplePush(ApplePushType.Alert) 
     With push
         .AddAlert(strTitle, strSubtitle, strBody)
         .AddToken(dicAPNS("token"))
         .AddSound(dicAPNS("sound"))
         .AddBadge(CInt(dicAPNS("badge")))
         .AddCategory(strCategory)
     End With
     Dim tResult = apns.SendAsync(push)   'and there it is...
     tResult.Wait()

When the push is sent, the `tResult` returns the results, which is parsed like this:

     dim strIsSuccessful as string = tResult.Result.IsSuccessful
     dim strReason as string = tResult.Result.Reason.ToString

This allows me to log and monitor the success or failure of the notification. 

I've been running the code this way for weeks with no problem. Maybe this will be helpful for others here.

**Comment by michaweiss10** [comment]
Dear Bill
Thank you very much !!

I am completely new at either c or vb.net ☹

Is seems to be that your solution might be very helpful for me
Could you please share an example of the whole vb.net code ?
I mean with the definition of the :BundleId; CertContent; keyId; TeamId

Thanks in advance!
Micha

**Comment by BillInOKC** [comment]
I'm happy to, with the understanding that I do not consider myself much of an advanced developer, so some of the code contained here may not make sense to some more experienced developers. All I know is that when I get something to work the way I need it to, it's locked in and I don't change it. "If it ain't broke, don't fix it."

Anyway, here is what I have. The name of the method is `TokenBasedConnection,` and it reads the message information from a `dictionary(of string, string)` passed in by the calling method.

    Shared Sub TokenBasedConnection(dicAPNS As Dictionary(Of String, String))  
        Dim apns As ApnsClient = Nothing
        Dim httpHandler As New WinHttpHandler
        httpHandler.SslProtocols = System.Security.Authentication.SslProtocols.Tls12
        Dim httpclient As HttpClient = New HttpClient(httpHandler)
           
The `dictionary` comes from the calling method, and it contains all message data, including the notification title, subtitle, and message body. It also contains the device token for the selected recipient, and for my purposes, it may contain a value for the badge and the name of the sound file to be played accompanying the notification. So here's that part:

      If dicAPNS.ContainsKey("badge") Then
            If String.IsNullOrEmpty(dicAPNS("badge")) Or Not IsNumeric(dicAPNS("badge")) Then
                dicAPNS("badge") = "0"
            End If
        Else
            dicAPNS.Add("badge", "0")
        End If

        If dicAPNS.ContainsKey("subtitle") Then
            If String.IsNullOrEmpty(dicAPNS("subtitle")) Then
                dicAPNS("subtitle") = Now    'if the sending method does not contain a value for the `subtitle` the value for `Now` (date & time) is used.
            End If
        Else
            dicAPNS.Add("subtitle", Now)
        End If
 
Then the system loads the certificate contents from the certificate file:

       Dim strCertContents As String = File.ReadAllText(My.Settings.APNSAuthKeyFilename)

And since this one application processes push notifications for three of my separate iOS apps, the dictionary also contains the Apple `bundleid` for the targeted app, which will make the following snippet make sense:

    Dim APNSoptions As New ApnsJwtOptions
    With APNSoptions
        .BundleId = dicAPNS("bundleid")
        .CertContent = strCertContents
        .KeyId = My.Settings.APNSKeyID
        .TeamId = My.Settings.APNSTeamID
    End With
     
At the top we declared `apns` as an `ApnsClient` object, set to `nothing`. Here is where we assign it:

    If IsNothing(apns) Then
        apns = ApnsClient.CreateUsingJwt(httpclient, APNSoptions)
    End If

This is the part that may raise some eyebrows, because I am not sure if it's something that I need to do or not. According to Apple specs, the certificate needs to be refreshed every 20 minutes. (Why? Because Apple just can't make things easy.) So this monitors the elapsed time since the previous refresh, and if it's over 20 minutes, it will re-assign the apns object like we did above:

    If DateDiff(DateInterval.Minute, My.Settings.LastUpdate, Now) > 20 Then
        apns = ApnsClient.CreateUsingJwt(httpclient, APNSoptions)
        My.Settings.LastUpdate = Now
        My.Settings.Save()
    End If

If this is unnecessary, or if there's a better way to do it, I am open to suggestions.

In my case, I use three iOS devices to test my apps, but one of them is designated a development device. So when I send a message to all three, dotAPNS needs to know when it's going to the sandbox. So the dictionary contains a key for "IsDev" which is a string version of "True" or False." If it's True, and it specifies the sandbox.

    If dicAPNS("isdev").ToLower = "true" Then
        apns.UseSandbox()
    End If

This next part is a little busy, and it may be more than you need. It runs through the dictionary to pick out the title, subtitle, and message body, plus the recipient's name and the push category (which is usually just nothing):

    Dim strTitle As String = ""
    If dicAPNS.ContainsKey("title") Then strTitle = dicAPNS("title")
    Dim strSubtitle As String = ""
    If dicAPNS.ContainsKey("subtitle") Then strSubtitle = dicAPNS("subtitle")
    Dim strBody As String = ""
    If dicAPNS.ContainsKey("body") Then strBody = dicAPNS("body")
    If dicAPNS.ContainsKey("name") Then strRecipientName = dicAPNS("name")
    Dim strCategory As String = "none"
    If dicAPNS.ContainsKey("category") Then strCategory = dicAPNS("category")

This next part allows the system to personalize the message, even if it's going out to a large number of people:

    strTitle = strTitle.Replace("%@", strRecipientName).Replace("%!", Split(strRecipientName, " ")(0))
    strSubtitle = strSubtitle.Replace("%@", strRecipientName).Replace("%!", Split(strRecipientName, " ")(0))
    strBody = strBody.Replace("%@", strRecipientName).Replace("%!", Split(strRecipientName, " ")(0))

If the writer of the message inserts the string `%@` in any of the message fields, it will replace that with the recipient's full name. If the string contains `%!` only the first name is used.

And now we come to the part that I included in my first message, when the push notification is passed on to Alex's dotAPNS code:

    With push
        .AddAlert(strTitle, strSubtitle, strBody)
        .AddToken(dicAPNS("token"))
        .AddSound(dicAPNS("sound"))
        .AddBadge(CInt(dicAPNS("badge")))
        .AddCategory(strCategory)
    End With
    Dim tResult = apns.SendAsync(push)
    tResult.Wait()

Then when the dotAPNS code has run its course, `tResult` gives me the response, which, among other things, contains the success or failure of the message that was sent, and a string that gives the reason why it failed. Usually it's because of a bad or expired device token

    dim strIsSuccessful as string = tResult.Result.IsSuccessful
    dim strReason as string = tResult.Result.Reason.ToString

And that's it, I guess. As I mentioned earlier, this way of doing it allows for so much more flexibility in sending a push notification, and returns results that make sense, than enclosing the whole method in an async wrapper.

I really hope this makes sense, and that it helps. I am happy to answer any further questions.

EDIT: It occurred to me that you specifically asked about bundleID, certID,etc. Those are items that you get from the Apple developer site. BundleID is the unique name given to the specific iOS app that you are targeting; KeyID is something else you get from Apple, but at the moment I can't remember specifically what it is; the CertID is the APNS certificate that apple provides, again on their developer website. dotAPNS allows for importing the certificate contents, which is text-based, and is loaded above using a text file reader function in VB; Team ID is the name of the development team working on the apps -- in my case, it's the name of the company that I work for. I probably should mention that all of my apps are Enterprise apps, meaning that they are developed for use solely by the company that I work for. I have no apps in the app store, and I wouldn't begin to know how to do that if I needed to.

**Comment by michaweiss10** [comment]
Thank you very much!

**Comment by alexalok** [comment]
@BillInOKC, thanks for a detailed description! I have just a little nitpick regarding JWT expiration. 

> This is the part that may raise some eyebrows, because I am not sure if it's something that I need to do or not. According to Apple specs, the certificate needs to be refreshed every 20 minutes. (Why? Because Apple just can't make things easy.) So this monitors the elapsed time since the previous refresh, and if it's over 20 minutes, it will re-assign the apns object like we did above:
> 
> ```
> If DateDiff(DateInterval.Minute, My.Settings.LastUpdate, Now) > 20 Then
>     apns = ApnsClient.CreateUsingJwt(httpclient, APNSoptions)
>     My.Settings.LastUpdate = Now
>     My.Settings.Save()
> End If
> ```

In fact, you do not need to do this yourself because [dotAPNS refreshes JWT automagically](https://github.com/alexalok/dotAPNS/blob/4086262e3cbb9ea23d5f84a0a718d14c145827a9/dotAPNS/ApnsClient.cs#L296).

Again, your code is not wrong in any way, just excessive.

**Comment by BillInOKC** [comment]
Good, thank you for the tip!

**Comment by michaweiss10** [comment]
Bill,

I tried to simplify your code as written ahead

It does not work ☹

tResult does not get any values

what did I miss?

Thanks!

Micha


Imports System
Imports System.Net.Http
Imports System.IO

'Imports System.CodeDom.Compiler
'Imports System.ComponentModel
'Imports System.ComponentModel.Design
Imports System.Security.Authentication
'Imports System.Security.Cryptography.X509Certificates

Imports dotAPNS

Public Class Snippet

      Public Shared Function TokenBasedConnection()

      AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false)


      Dim apns As ApnsClient = Nothing
    Dim httpHandler As New WinHttpHandler
      httpHandler.SslProtocols = System.Security.Authentication.SslProtocols.Tls12
    Dim httpClientForPush As HttpClient = New HttpClient(httpHandler)


      Dim strCertContents As String = le.ReadAllText(“\\localpath\AuthKey_7L2KFJVZ34.p8<file://localpath/AuthKey_7L2KFJVZ34.p8>”)


      Dim APNSoptions As New ApnsJwtOptions
      With APNSoptions
            .BundleId = "my-BundleId "
            .CertContent = strCertContents
            .KeyId = " my-KeyId "
            .TeamId = "my-TeamId"
      End With

      apns = ApnsClient.CreateUsingJwt(httpClientForPush, APNSoptions)


      Dim push As New ApplePush(ApplePushType.Alert)

      With push
      .AddAlert("Title","Subtitle","body")
      .AddToken("my device token")
            ' .AddSound("sound")
            ' .AddBadge("badge")
            ' .AddCategory("strCategory")
      End With



      Dim tResult = apns.SendAsync(push)

      tResult.Wait()

      dim strIsSuccessful as string = tResult.Result.IsSuccessful
      dim strReason as string = tResult.Result.Reason.ToString





      End Function

End Class

**Comment by BillInOKC** [comment]
Hi Micha, Sorry you're having trouble. A quick scan of your code shows a typo on the line reading the certificate contents:

    Dim strCertContents As String = le.ReadAllText(“\\localpath\AuthKey_7L2KFJVZ34.p8<file://localpath/AuthKey_7L2KFJVZ34.p8>”)

Where "**le**.ReadAllText" should be "**File**.ReadAllText."

...which would return an empty string for the certificate contents. 

Now, this may just be a typo in your transcription, and not the actual problem. At the moment, it's the only thing that jumps out at me, and under normal circumstances in the development environment, that would be flagged as an error. But I will look over the rest of the code and see what else I can find.

**Comment by michaweiss10** [comment]
Bill

It is a typo in my  transcription, and not an actual problem 😊

In the original code the line is:

Dim strCertContents As String = File.ReadAllText(“\\localpath\AuthKey_7L2KFJVZ34.p8”<file://132.64.7.153/DevRoot/Dev/magic/MagicXpA/VerForProd/HToolsXpA/dotAPNS/AuthKey_7L2KFJVZ34.p8>)

Thank you very much!

micha

**Comment by BillInOKC** [comment]
This is something odd, and I don't know what it means. Maybe someone here can help me out. Referring again to your line that reads the certificate contents:

      Dim strCertContents As String = le.ReadAllText(“\\localpath\AuthKey_7L2KFJVZ34.p8<file://localpath/AuthKey_7L2KFJVZ34.p8>”)

Notice how this view renders the quotation marks, compared to other lines that contain quotes, i.e.:

    With push
        .AddAlert("Title","Subtitle","body")
        .AddToken("my device token")
        ' .AddSound("sound")
        ' .AddBadge("badge")
        ' .AddCategory("strCategory")
    End With

In the ReadAllText line the quotes are rendered as literary quotation marks, with typical opening and closing formats. Again, I don't know if it means anything.

Beyond these two anomalies, I can't see anything that would cause you any problems. I hope we can work it out!

**Comment by michaweiss10** [comment]
Thank you very much!
I will update you
Micha
