### ISSUE TITLE
Notification is sent, but always in the background

### ISSUE THREAD

**Issue by Faisal0sal** [alexalok/dotAPNS#9]
`ApplePushAlert pushAlert = new ApplePushAlert("TITLE", "BODY");
            
            ApplePush push = ApplePush
                .CreateAlert(pushAlert)
                .AddToken("12b5bb89699ca2a0068f4b01444d0cc49670c489b8e661c37e9029de3101141c");

            var apns = ApnsClient.CreateUsingJwt(new HttpClient(), options);

            ApnsResponse response = await apns.Send(push);`

I'm using the code above to send notifications to my passes. the notification is sent but I can't see it, it's always in the background.

Am I doing something wrong?

**Comment by alexalok** [comment]
Greetings!

At the first glance, everything looks OK. Perhaps you could check the `response` variable? If there is an error with the push send, it will be reflected in `ReasonString` property of the `ApnsResponse`.

**Comment by Faisal0sal** [comment]
`{
  "response": {
    "reason": 0,
    "reasonString": null,
    "isSuccessful": true
  }
}`


It looks like there's nothing wrong here. Would a sandbox apns affect this maybe?

**Comment by Faisal0sal** [comment]
nvm I'm not using sandbox

**Comment by alexalok** [comment]
If you were using sandbox with the production tokens than `response` would contain an error, so this is out of question indeed.

**Comment by Faisal0sal** [comment]
I figured out the issue. I'm developing a wallet pass and with wallet passes the alerts are actually ignored and the display message is a change in the wallet fields.

Thanks @alexalok  and sorry to bother you

**Comment by alexalok** [comment]
Glad to hear that you sorted this out! Thank you for sharing the root cause as well.

**Comment by lxalln** [comment]
> I figured out the issue. I'm developing a wallet pass and with wallet passes the alerts are actually ignored and the display message is a change in the wallet fields.
> 
> Thanks @alexalok and sorry to bother you

@Faisal0sal did you manage to get this working?

I am using dotAPNS to do the same as you, update my passes. However, although the response suggests success, I'm seeing no updates to the passes, and no requests to the `GET /v1/devices/{deviceLibraryIdentifier}/registrations/{passTypeIdentifier}?passesUpdatedSince={tag}` endpoint.

I'm struggling to find any information beyond that, any help would be appreciated.

**Comment by Jawvig** [comment]
@lxalln @Faisal0sal Did either of you get wallet update notifications working? We've been banging our heads against a brick wall on this.

In order to use the latest version of this library to send a notification that matches what little documentation there is out there for this and that returned a success response, we had to modify the `ApplePush` class so that it could be used to create a totally empty body to the POST (well, just `{}` rather than `{ "aps": {} }`.

We also modified `ApnClient` so we could elect to skip the `apns-push-type` and `apns-priority` headers. (EDIT: This didn't appear to make any difference - we also tried leaving them in and using both `background` and `alert`, receiving a 200 response for any combo)

However, whilst the notification gets a successful response, like @lxalln we never see a call to the update service. And we know that pull-to-refresh works fine on the passes by calling that same service.

It feels like there are about six people in the world who have got this working.

**Comment by lxalln** [comment]
@Jawvig No, I never managed to get it working with this library.

But we do have it working in production with: https://github.com/Redth/PushSharp
Feel free to drop me an email (i.am @ username.com) if you get stuck, and I'll try and figure out how we did it :)

**Comment by pauldunstone** [comment]
@lxalln @Jawvig 

Did you ever manage to get this library working with Apple Wallet?
We got it working by setting the bundle id to be the name of the pass certificate i.e. "pass.com.whatever" and set the push type to background.
